// Layer registry entries — generators group (OSM plants/generators, EIA plants).
import type { LayerDef } from '../types.js';

export const generatorLayers: LayerDef[] = [
  {
    id:            "osm-plants-points",
    urlCode:       "OPL",
    label:         "OSM Plants",
    group:         "generators",
    sourceId:      "osm",
    swatch:        "#10b981",
    defaultOn:     false,
    fuelLayer:     true,
    mapLayerIds:   ["osm-plant-icons", "osm-plant-heat"],
    heatLayerId:   "osm-plant-heat",
    genModeCode:   "o",
    filterType:  "fuel_osm",
    filterField: "source",
    downloads: {
      csv: "data/releases/osm-plants-points.zip",
    },
  },
  {
    id:            "osm-plants-polygons",
    urlCode:       "OPP",
    label:         "OSM Plant Polygons",
    group:         "generators",
    sourceId:      "osm",
    swatch:        "#10b981",
    defaultOn:     false,
    fuelLayer:     true,
    hoverField:    "osm_id",
    mapLayerIds:   ["osm-plants-polygons-fill", "osm-plants-polygons-outline"],
    filterType:  "fuel_osm",
    filterField: "source",
    downloads: {
      geojson: "data/releases/osm-plants-polygons.zip",
      shp: "data/releases/osm-plants-polygons-shp.zip",
    },
  },
  {
    id:            "osm-generators",
    urlCode:       "OGN",
    label:         "OSM Generators",
    group:         "generators",
    sourceId:      "osm",
    swatch:        "#3b82f6",
    defaultOn:     false,
    fuelLayer:     true,
    mapLayerIds:   ["osm-gen-circles"],
    filterType:  "fuel_osm",
    filterField: "source",
    downloads: {
      csv: "data/releases/osm-generators.zip",
    },
  },
  {
    id:            "eia-generators",
    urlCode:       "EGN",
    label:         "EIA Plants",
    group:         "generators",
    sourceId:      "eia",
    swatch:        "#fbbf24",
    defaultOn:     false,
    fuelLayer:     true,
    mapLayerIds:   ["eia-gen-circles", "eia-gen-heat"],
    heatLayerId:   "eia-gen-heat",
    genModeCode:   "e",
    yearFilterLayer: true,
    filterType:    "fuel_eia",
    filterField:   "energy_source",
    bucketField:      "gen_status",
    filterGroupCode:  "s",
    filterBuckets: [
      { id: "existing",   label: "Existing",           color: "#fbbf24", urlCode: "e" },
      { id: "retirement", label: "Planned Retirement", color: "#f97316", urlCode: "r" },
      { id: "retired",    label: "Retired",            color: "#6b7280", urlCode: "d", default: false },
      { id: "proposed",   label: "Proposed",           color: "#22c55e", urlCode: "p", default: false },
    ],
    downloads: {
      csv: "data/releases/eia-generators.zip",
    },
  },
];
