// Layer registry entries — regions, load context, and test layers.
import { POP_RAMP_STOPS, POP_LOG_MAX } from '../colors/ramps.js';
import type { LayerDef } from '../types.js';
import { convDensity, densityLabel } from '../units.js';

export const regionLayers: LayerDef[] = [
  // ── Load context ─────────────────────────────────────────────────────────────
  {
    id:            "osm-datacenters",
    urlCode:       "DCT",
    label:         "OSM Data Centers",
    titleKey:      "layer.osmDatacenters",
    group:         "load",
    sourceId:      "osm",
    swatch:        "#6366f1",
    defaultOn:     false,
    mapLayerIds:   ["osm-dc-circles", "osm-dc-heat", "osm-dc-clusters", "osm-dc-cluster-count", "osm-dc-points", "osm-dc-heat-points"],
    heatLayerId:   "osm-dc-heat",
    genModeCode:   "d",
    defaultMode:   "icons",
    modes: [
      { id: "icons",    label: "Points",   layers: ["osm-dc-points"] },
      { id: "clusters", label: "Clusters", layers: ["osm-dc-clusters", "osm-dc-cluster-count", "osm-dc-circles"] },
      { id: "heat",     label: "Heatmap",  layers: ["osm-dc-heat", "osm-dc-heat-points"] },
    ],
    downloads: {
      csv: "data/releases/osm-datacenters.zip",
    },
  },
  {
    id:            "worldpop-pop-density",
    urlCode:       "POP",
    label:         "Population Density",
    titleKey:      "layer.popDensity",
    group:         "load",
    sourceId:      "worldpop",
    swatch:        `rgb(${POP_RAMP_STOPS[2][1]})`,
    ramp:          {
      stops: POP_RAMP_STOPS, max: POP_LOG_MAX, minLabel: "0",
      // Stops are log10(1+x) transformed for tiling, so the label leaves log
      // space before converting. Rounded to the nearest thousand in display
      // units — POP_LOG_MAX is itself an approximate clamp, so the label
      // carries no more precision than the ramp does.
      fmt: (v, mark = "") =>
        `${(Math.round(convDensity(10 ** v - 1) / 1000) * 1000).toLocaleString()}${mark} ${densityLabel()}`,
    },
    defaultOn:     false,
    mapLayerIds:   ["worldpop-pop-density"],
    downloads: {
      tif: "data/releases/worldpop-pop-density.zip",
    },
  },

  // ── Regions ──────────────────────────────────────────────────────────────────
  {
    id:           "nerc-regions",
    urlCode:      "NRC",
    label:        "HIFLD NERC Regions",
    titleKey:     "layer.nercRegions",
    group:        "regions",
    sourceId:     "hifld-nerc",
    swatch:       "#3b82f6",
    defaultOn:    false,
    hoverField:   "sub_nm",
    mapLayerIds:  ["nerc-fill", "nerc-outline"],
    downloads: {
      geojson: "data/releases/nerc-regions.zip",
      shp: "data/releases/nerc-regions-shp.zip",
    },
  },
  {
    id:           "control-areas",
    urlCode:      "CTA",
    label:        "HIFLD Balancing Authorities",
    titleKey:     "layer.controlAreas",
    group:        "regions",
    sourceId:     "hifld-ba",
    swatch:       "#64748b",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["ba-fill", "ba-outline", "ba-label"],
    downloads: {
      geojson: "data/releases/control-areas.zip",
      shp: "data/releases/control-areas-shp.zip",
    },
  },
  {
    id:           "eia-ba",
    urlCode:      "EBA",
    label:        "EIA Balancing Authorities",
    titleKey:     "layer.eiaBa",
    group:        "regions",
    sourceId:     "eia-ba",
    swatch:       "#14b8a6",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["eiaba-fill", "eiaba-outline", "eiaba-label"],
    downloads: {
      geojson: "data/releases/eia-ba.zip",
      shp: "data/releases/eia-ba-shp.zip",
    },
  },
  {
    id:           "retail-territories",
    urlCode:      "RTL",
    label:        "HIFLD Retail Territories",
    titleKey:     "layer.retailTerritories",
    group:        "regions",
    sourceId:     "hifld-retail",
    swatch:       "#f97316",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["retail-fill", "retail-outline"],
    downloads: {
      geojson: "data/releases/retail-territories.zip",
      shp: "data/releases/retail-territories-shp.zip",
    },
  },
  {
    id:           "countries",
    urlCode:      "CRY",
    label:        "Countries",
    titleKey:     "layer.countries",
    group:        "regions",
    sourceId:     "cgaz-adm0",
    swatch:       "#8250b0",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["countries-fill", "countries-outline", "countries-label"],
    downloads: {},
  },
  {
    id:           "admin1",
    urlCode:      "ADM",
    label:        "States / Provinces",
    titleKey:     "layer.admin1",
    group:        "regions",
    sourceId:     "cgaz-adm1",
    swatch:       "#1f8f96",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["admin1-fill", "admin1-outline", "admin1-label"],
    downloads: {},
  },
  {
    id:           "us-states",
    urlCode:      "STA",
    label:        "Census States",
    titleKey:     "layer.usStates",
    group:        "regions",
    sourceId:     "census-states",
    swatch:       "#2f6fad",
    defaultOn:    false,
    hoverField:   "name",
    mapLayerIds:  ["us-states-fill", "us-states-outline", "us-states-label"],
    downloads: {},
  },
  {
    id:           "us-counties",
    urlCode:      "CTY",
    label:        "Census Counties",
    titleKey:     "layer.usCounties",
    group:        "regions",
    sourceId:     "census-counties",
    swatch:       "#8a8a2e",
    defaultOn:    false,
    hoverField:   "GEOID",
    mapLayerIds:  ["us-counties-fill", "us-counties-outline", "us-counties-label"],
    downloads: {},
  },
  {
    id:           "us-zcta",
    urlCode:      "ZCT",
    label:        "Census ZIP Codes (ZCTA)",
    titleKey:     "layer.usZcta",
    group:        "regions",
    sourceId:     "census-zcta",
    swatch:       "#c04a5e",
    defaultOn:    false,
    hoverField:   "zcta5",
    mapLayerIds:  ["us-zcta-fill", "us-zcta-outline", "us-zcta-label"],
    downloads: {},
  },

];
