// Layer registry entries — substations and transmission lines.
import type { LayerDef } from '../types.js';

export const transmissionLayers: LayerDef[] = [
  // ── Substations ──────────────────────────────────────────────────────────────
  {
    id:            "osm-substations-points",
    urlCode:       "OSP",
    label:         "OSM Substations",
    group:         "substations",
    sourceId:      "osm",
    swatch:        "#f97316",
    defaultOn:     false,
    voltageLayer:  true,
    mapLayerIds:   ["osm-substations-points-hv", "osm-substations-points-lv", "osm-substations-label"],
    filterType:    "kv",
    filterField:   "nominal_kv",
    downloads: {
      csv: "data/releases/osm-substations-points.zip",
    },
  },
  {
    id:            "osm-substations-polygons",
    urlCode:       "OSR",
    label:         "OSM Sub Polygons",
    group:         "substations",
    sourceId:      "osm",
    swatch:        "#f97316",
    defaultOn:     false,
    voltageLayer:  true,
    hoverField:    "osm_id",
    mapLayerIds:   ["osm-substations-polygons-fill", "osm-substations-polygons-outline"],
    filterType:    "kv",
    filterField:   "nominal_kv",
    downloads: {
      geojson: "data/releases/osm-substations-polygons.zip",
      shp: "data/releases/osm-substations-polygons-shp.zip",
    },
  },
  {
    id:            "hifld-substations",
    urlCode:       "HSP",
    label:         "HIFLD Substations",
    group:         "substations",
    sourceId:      "hifld-substations",
    swatch:        "#a78bfa",
    defaultOn:     false,
    voltageLayer:  true,
    mapLayerIds:   ["hifld-substations-hv", "hifld-substations-lv", "hifld-substations-label"],
    filterType:    "kv",
    filterField:   "max_kv",
    downloads: {
      csv: "data/releases/hifld-substations.zip",
    },
  },

  // ── Transmission lines ───────────────────────────────────────────────────────
  {
    id:                  "osm-transmission-lines",
    urlCode:             "OTL",
    label:               "OSM Lines",
    group:               "transmission",
    sourceId:            "osm",
    swatch:              "#3b82f6",
    defaultOn:           true,
    voltageLayer:        true,
    lineHighlightKeys:   ["name"],
    mapLayerIds:         ["osm-transmission-lines-hv", "osm-transmission-lines-mv", "osm-transmission-lines-lv", "osm-transmission-lines-unknown", "osm-transmission-lines-label"],
    filterType:    "kv",
    filterField:   "nominal_kv",
    downloads: {
      geojson: "data/releases/osm-transmission-lines.zip",
      shp: "data/releases/osm-transmission-lines-shp.zip",
    },
  },
  {
    id:                  "hifld-transmission-lines",
    urlCode:             "HTL",
    label:               "HIFLD Lines",
    group:               "transmission",
    sourceId:            "hifld-power",
    swatch:              "#ef4444",
    defaultOn:           false,
    voltageLayer:        true,
    lineHighlightKeys:   ["SUB_1", "SUB_2"],
    mapLayerIds:         ["hifld-transmission-lines-hv", "hifld-transmission-lines-mv", "hifld-transmission-lines-lv", "hifld-transmission-lines-unknown"],
    filterType:    "kv",
    filterField:   "VOLTAGE",
    downloads: {
      geojson: "data/releases/hifld-transmission-lines.zip",
      shp: "data/releases/hifld-transmission-lines-shp.zip",
    },
  },
  {
    id:             "ogf-planned-transmission",
    urlCode:        "OGF",
    label:          "OGF Planned Lines",
    group:          "transmission",
    sourceId:       "ogf",
    swatch:         "#06b6d4",
    defaultOn:      false,
    ogfStatusLayer: true,
    mapLayerIds:    ["ogf-planned-lines-casing", "ogf-planned-lines"],
    downloads: {
      url: "https://ourgridfuture.org",
    },
  },
  {
    id:          "wecc-paths",
    urlCode:     "WPT",
    label:       "WECC Paths",
    group:       "transmission",
    sourceId:    "wecc-paths",
    swatch:      "#eab308",
    defaultOn:   false,
    mapLayerIds: ["wecc-path-corridors", "wecc-path-corridors-outline",
                  "wecc-path-lines-highlight", "wecc-paths-circles", "wecc-paths-label"],
    downloads: {
      geojson: "data/releases/wecc-paths.zip",
      url: "https://www.wecc.org/sites/default/files/documents/progress_report/2026/2026%20Path%20Rating%20Catalog%20Public_V3.pdf",
    },
  },
];
